# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 380a8f04d2ce905d1eb0a60cd23b7b05bc25c552bd9aeec9277a7ab308956b6af89f1beb921dd5f7e65d99c6d3b7228ab652d5b46a7ceade0ab3453981c9d83d

test:
  secret_key_base: 679f0ecf137d3e768f425dd47adc77a8c163fdc55b1146f3d05584b0fdfbc9dea972af34e3869b31c380a43827dc5dfd0e27978d554240becdb0f55d44abd326

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
